export enum ConfigEnum {
  PORT = 'PORT',
  DB_URI = 'DB_URI',
  JWT_SECRET = 'JWT_SECRET',
  TMDB_URI = 'TMDB_URI',
  TMDB_API_KEY_V3_AUTH = 'TMDB_API_KEY_V3_AUTH',
  TMDB_API_KEY_V4_AUTH = 'TMDB_API_KEY_V4_AUTH',
  SENDGRID_API_KEY = 'SENDGRID_API_KEY',
  API_IBM_TRANSLATOR = 'API_IBM_TRANSLATOR',
  API_URL_IBM_TRANSLATOR = 'API_URL_IBM_TRANSLATOR',
  REDIS_ENDPOINT = 'REDIS_ENDPOINT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  REDIS_DATABASE = 'REDIS_DATABASE'
}
